### ISSUE TITLE
Issue with one-click Heroku deploy

### ISSUE THREAD

**Issue by tashua314** [rutan/togelack#8]
Error on "Run scripts & scale dynos"

```
rake aborted!
NoMethodError: undefined method `each' for nil:NilClass
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.1/lib/mongo/cluster.rb:115:in `initialize'
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.1/lib/mongo/client.rb:337:in `new'
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.1/lib/mongo/client.rb:337:in `create_from_addresses'
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.1/lib/mongo/client.rb:202:in `initialize'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.1/lib/mongoid/clients/factory.rb:64:in `new'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.1/lib/mongoid/clients/factory.rb:64:in `create_client'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.1/lib/mongoid/clients/factory.rb:27:in `create'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.1/lib/mongoid/clients.rb:67:in `with_name'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.1/lib/mongoid/clients.rb:118:in `mongo_client'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.1/lib/mongoid/clients.rb:140:in `collection'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.1/lib/mongoid/clients/options.rb:177:in `method_missing'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.1/lib/mongoid/indexable.rb:37:in `block in create_indexes'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.1/lib/mongoid/indexable.rb:31:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.1/lib/mongoid/indexable.rb:31:in `create_indexes'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.1/lib/mongoid/tasks/database.rb:20:in `block in create_indexes'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.1/lib/mongoid/tasks/database.rb:17:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.1/lib/mongoid/tasks/database.rb:17:in `create_indexes'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.1/lib/mongoid/tasks/database.rake:8:in `block (3 levels) in <top (required)>'
Tasks: TOP => db:mongoid:create_indexes
(See full trace by running task with --trace)
```

Build log:
```
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.2.4
-----> Installing dependencies using bundler 1.11.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Fetching gem metadata from https://rubygems.org/..........
       Fetching version metadata from https://rubygems.org/...
       Fetching dependency metadata from https://rubygems.org/..
       Using rake 10.4.2
       Installing i18n 0.7.0
       Installing json 1.8.3 with native extensions
       Installing minitest 5.8.3
       Installing thread_safe 0.3.5
       Installing builder 3.2.2
       Installing erubis 2.7.0
       Installing mini_portile2 2.0.0
       Installing rack 1.6.4
       Installing mime-types 2.99
       Installing arel 6.0.3
       Installing addressable 2.4.0
       Installing ast 2.1.0
       Installing awesome_print 1.6.1
       Installing coderay 1.1.0
       Installing debug_inspector 0.0.2 with native extensions
       Installing fastercsv 1.5.5
       Installing tilt 1.4.1
       Installing multi_json 1.11.2
       Installing sexp_processor 4.6.0
       Installing highline 1.7.8
       Installing safe_yaml 1.0.4
       Installing sass 3.4.20
       Installing temple 0.7.6
       Installing terminal-table 1.5.2
       Installing bson_ext 1.5.1 with native extensions
       Installing bson 4.0.0 with native extensions
       Installing uniform_notifier 1.9.0
       Installing byebug 8.2.1 with native extensions
       Installing chunky_png 1.3.5
       Installing rspec-support 3.4.1
       Installing rb-fsevent 0.9.6
       Installing diff-lcs 1.2.5
       Installing hike 1.2.3
       Installing thor 0.19.1
       Installing ffi 1.9.10 with native extensions
       Installing docile 1.1.5
       Installing dotenv 2.0.2
       Installing request_store 1.2.1
       Installing escape_utils 1.0.1 with native extensions
       Installing eventmachine 1.0.8 with native extensions
       Installing execjs 2.6.0
       Installing multipart-post 2.0.0
       Installing websocket-extensions 0.1.2
       Installing formatador 0.2.5
       Installing gemoji 2.1.0
       Installing growl 1.0.3
       Installing lumberjack 1.0.9
       Installing nenv 0.2.0
       Installing shellany 0.0.1
       Installing slop 3.6.0
       Using bundler 1.11.2
       Installing method_source 0.8.2
       Installing powerpack 0.1.1
       Installing guard-compat 1.2.1
       Installing ruby-progressbar 1.7.5
       Installing rainbow 2.0.0
       Installing hashdiff 0.2.3
       Installing tins 1.6.0
       Installing hashie 3.4.3
       Installing http_accept_language 2.0.5
       Installing simplecov-html 0.10.0
       Installing yard 0.8.7.6
       Installing spring 1.6.0
       Installing jwt 1.5.2
       Installing origin 2.1.1
       Installing libv8 3.16.14.13
       Installing multi_xml 0.5.5
       Installing rails_serve_static_assets 0.0.4
       Installing puma 2.15.3 with native extensions
       Installing rails_stdout_logging 0.0.4
       Installing redis 3.2.2
       Installing ref 2.0.0
       Installing tzinfo 1.2.2
       Installing ci_reporter 2.0.0
       Installing rack-test 0.6.3
       Installing nokogiri 1.6.7 with native extensions
       Installing rack-mini-profiler 0.9.8
       Installing mail 2.6.3
       Installing better_errors 2.1.1
       Installing parser 2.2.3.0
       Installing haml 4.0.7
       Installing binding_of_caller 0.7.2 with native extensions
       Installing ruby_parser 3.7.2
       Installing crack 0.4.3
       Installing slim 3.0.6
       Installing compass-core 1.0.3
       Installing compass-import-once 1.0.5
       Installing font-awesome-sass 4.5.0
       Installing mongo 2.2.1
       Installing rspec-core 3.4.1
       Installing rspec-expectations 3.4.0
       Installing rspec-mocks 3.4.0
       Installing sprockets 2.12.4
       Installing tapp 1.5.0
       Installing libnotify 0.9.1
       Installing rb-inotify 0.9.5
       Installing uglifier 2.7.2
       Installing faraday 0.9.2
       Installing websocket-driver 0.6.3 with native extensions
       Installing notiffany 0.0.8
       Installing pry 0.10.3
       Installing omniauth 1.2.2
       Installing simplecov 0.11.1
       Installing spring-commands-rspec 1.0.4
       Installing rails_12factor 0.0.3
       Installing redis-store 1.1.7
       Installing therubyracer 0.12.2 with native extensions
       Installing activesupport 4.2.0
       Installing astrolabe 1.3.1
       Installing ruby2ruby 2.2.0
       Installing webmock 1.22.3
       Installing rspec-its 1.2.0
       Installing rspec 3.4.0
       Installing loofah 2.0.3
       Installing compass 1.0.3
       Installing listen 3.0.5
       Installing faraday_middleware 0.10.0
       Installing oauth2 1.0.0
       Installing pry-byebug 3.3.0
       Installing faye-websocket 0.9.2
       Installing pry-rails 0.3.4
       Installing pry-doc 0.8.0
       Installing pry-stack_explorer 0.4.9.2
       Installing simplecov-rcov 0.2.3
       Installing redis-rack 1.5.0
       Installing rails-deprecated_sanitizer 1.0.3
       Installing globalid 0.3.6
       Installing activemodel 4.2.0
       Installing bullet 4.14.10
       Installing factory_girl 4.5.0
       Installing redis-activesupport 4.1.5
       Installing html-pipeline 1.11.0
       Installing sprockets-redirect 0.3.0
       Installing rubocop 0.35.1
       Installing brakeman 3.1.3
       Installing ci_reporter_rspec 1.0.0
       Installing rails-html-sanitizer 1.0.2
       Installing guard 2.13.0
       Installing omniauth-oauth2 1.3.1
       Installing slack-api 1.2.1
       Installing activejob 4.2.0
       Installing rails-dom-testing 1.0.7
       Installing activerecord 4.2.0
       Installing mongoid 5.0.1
       Installing guard-brakeman 0.8.3
       Installing slack_markdown 0.1.2
       Installing guard-bundler 2.1.0
       Installing guard-rubocop 1.2.0
       Installing guard-rspec 4.6.4
       Installing omniauth-slack 2.2.0
       Installing actionview 4.2.0
       Installing actionpack 4.2.0
       Installing sprockets-rails 2.3.3
       Installing actionmailer 4.2.0
       Installing railties 4.2.0
       Installing draper 2.1.0
       Installing redis-actionpack 4.0.1
       Installing kaminari 0.16.3
       Installing sass-rails 5.0.1
       Installing dotenv-rails 2.0.2
       Installing factory_girl_rails 4.5.0
       Installing quiet_assets 1.1.0
       Installing rspec-rails 3.4.0
       Installing jquery-rails 4.0.5
       Installing rails-i18n 4.0.7
       Installing rails 4.2.0
       Installing slim-rails 3.0.1
       Installing redis-rails 4.0.0
       Installing ikazuchi 0.1.7
       Installing compass-rails 2.0.5
       Bundle complete! 28 Gemfile dependencies, 171 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into ./vendor/bundle.
       Post-install message from haml:
       HEADS UP! Haml 4.0 has many improvements, but also has changes that may break
       your application:
       * Support for Ruby 1.8.6 dropped
       * Support for Rails 2 dropped
       * Sass filter now always outputs <style> tags
       * Data attributes are now hyphenated, not underscored
       * html2haml utility moved to the html2haml gem
       * Textile and Maruku filters moved to the haml-contrib gem
       For more info see:
       http://rubydoc.info/github/haml/haml/file/CHANGELOG.md
       Post-install message from compass:
       Compass is charityware. If you love it, please donate on our behalf at http://umdf.org/compass Thanks!
       Post-install message from html-pipeline:
       -------------------------------------------------
       Thank you for installing html-pipeline!
       You must bundle Filter gem dependencies.
       See html-pipeline README.md for more details.
       https://github.com/jch/html-pipeline#dependencies
       -------------------------------------------------
       Bundle completed (63.55s)
       Cleaning up the bundler cache.
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       I, [2016-05-20T03:25:55.155146 #3893]  INFO -- : Writing /tmp/build_0257947a74a14343ce510e4726e04839/rutan-togelack-f7c5fb7/public/assets/application-f6b9dac9aae7a07f39c9076d79a3b74e.js
       I, [2016-05-20T03:26:00.210123 #3893]  INFO -- : Writing
:
:
:
 /tmp/build_0257947a74a14343ce510e4726e04839/rutan-togelack-f7c5fb7/public/assets/font-awesome/fontawesome-webfont-be0584438c9b22a95d72e4aaebfe12ed.woff2
       Asset precompilation completed (12.96s)
       Cleaning assets
       Running: rake assets:clean
-----> Discovering process types
       Procfile declares types     -> web
       Default types for buildpack -> console, rake, worker
-----> Compressing...
       Done: 66.2M
-----> Launching...
       Released v7
       https://arcane-brushlands-79861.herokuapp.com/ deployed to Heroku
```

**Comment by rutan** [comment]
Thanks report!
I fixed this problem https://github.com/rutan/togelack/pull/9/files 🙇

**Comment by tashua314** [comment]
THX!!!!:bow:
